using System.Text;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Game001.CodeGenerator;

public sealed class EcsRegistrationGenerationStep : ICodeGenerationStep
{
    public string Name => "ecs-registration";

    public CodeGenerationResult Execute(
        CodeGenerationContext context,
        CSharpSourceCatalog coreSources)
    {
        var componentTypes = new SortedSet<string>(StringComparer.Ordinal);
        foreach (CSharpSourceFile sourceFile in coreSources.Files)
        {
            foreach (StructDeclarationSyntax declaration in sourceFile.Root
                         .DescendantNodes()
                         .OfType<StructDeclarationSyntax>())
            {
                if (CSharpSyntax.FindAttribute(declaration, "EcsReplicatedComponent") == null)
                {
                    continue;
                }

                EnsureSharedComponent(context, sourceFile, declaration);
                componentTypes.Add(CSharpSyntax.GetTypeName(declaration));
            }
        }

        string outputPath = Path.Combine(
            context.GeneratedRuntimeDirectory,
            "Game001EcsRegistration.g.cs");
        GeneratedFileChange change = GeneratedFileWriter.WriteIfChanged(
            outputPath,
            GenerateRegistration(componentTypes));
        return change switch
        {
            GeneratedFileChange.Created => new CodeGenerationResult(1, 0, 0),
            GeneratedFileChange.Updated => new CodeGenerationResult(0, 1, 0),
            _ => new CodeGenerationResult(0, 0, 1),
        };
    }

    private static void EnsureSharedComponent(
        CodeGenerationContext context,
        CSharpSourceFile sourceFile,
        StructDeclarationSyntax declaration)
    {
        string relativePath = Path.GetRelativePath(context.UnityRuntimeDirectory, sourceFile.FullPath);
        if (relativePath == ".." ||
            relativePath.StartsWith(".." + Path.DirectorySeparatorChar, StringComparison.Ordinal) ||
            relativePath.StartsWith(".." + Path.AltDirectorySeparatorChar, StringComparison.Ordinal))
        {
            throw new InvalidOperationException(
                $"replicated ECS component must be inside Game001.Core/UnityPackage/Runtime: {sourceFile.RelativePath}");
        }

        if (declaration.TypeParameterList != null)
        {
            throw new InvalidOperationException(
                $"generic replicated ECS component is not supported: {declaration.Identifier.ValueText}");
        }
    }

    private static string GenerateRegistration(IEnumerable<string> componentTypes)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine();
        builder.AppendLine("namespace Game001.Core.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    public static class Game001EcsRegistration");
        builder.AppendLine("    {");
        builder.AppendLine("        public static global::GameServer.Core.Ecs.EcsComponentRegistry CreateRegistry()");
        builder.AppendLine("        {");
        builder.AppendLine("            var registry = new global::GameServer.Core.Ecs.EcsComponentRegistry();");
        builder.AppendLine("            RegisterAll(registry);");
        builder.AppendLine("            return registry;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static void RegisterAll(global::GameServer.Core.Ecs.EcsComponentRegistry registry)");
        builder.AppendLine("        {");
        foreach (string componentType in componentTypes)
        {
            builder.Append("            registry.Register<global::");
            builder.Append(componentType);
            builder.AppendLine(">();");
        }

        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }
}
