using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace Game001.CodeGenerator;

public sealed class RoomMessageRegistrationGenerationStep : ICodeGenerationStep
{
    public string Name => "room-message-registration";

    public CodeGenerationResult Execute(
        CodeGenerationContext context,
        CSharpSourceCatalog coreSources)
    {
        RoomMessageCatalog messages = RoomMessageCatalog.Collect(coreSources);
        string outputPath = Path.Combine(
            context.RoomGeneratedDirectory,
            "Game001RoomMessageRegistration.g.cs");
        GeneratedFileChange change = GeneratedFileWriter.WriteIfChanged(
            outputPath,
            Generate(messages));
        return change switch
        {
            GeneratedFileChange.Created => new CodeGenerationResult(1, 0, 0),
            GeneratedFileChange.Updated => new CodeGenerationResult(0, 1, 0),
            _ => new CodeGenerationResult(0, 0, 1),
        };
    }

    private static string Generate(RoomMessageCatalog messages)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine();
        builder.AppendLine("namespace Game001.Room;");
        builder.AppendLine();
        builder.AppendLine("public sealed partial class Game001RoomWorker");
        builder.AppendLine("{");
        builder.AppendLine("    private global::GameServer.Core.Rooms.RoomRequestRouter CreateRequestRouter()");
        builder.AppendLine("    {");
        builder.AppendLine("        var router = new global::GameServer.Core.Rooms.RoomRequestRouter();");
        foreach (RoomRequestInfo request in messages.Requests)
        {
            AppendRequestRegistration(builder, request);
        }

        builder.AppendLine("        return router;");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("public static class Game001RoomCommandRegistration");
        builder.AppendLine("{");
        builder.AppendLine("    public static void RegisterAll(");
        builder.AppendLine("        global::GameServer.Core.Rooms.RoomCommandServerCenter center,");
        builder.AppendLine("        Game001RoomCommandHandlers handlers)");
        builder.AppendLine("    {");
        foreach (RoomCommandInfo command in messages.Commands)
        {
            builder.Append("        center.Register<global::");
            builder.Append(command.CommandType);
            builder.Append(">(handlers.");
            builder.Append(command.HandlerName);
            builder.AppendLine(");");
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendRequestRegistration(StringBuilder builder, RoomRequestInfo request)
    {
        if (request.Kind == "Worker")
        {
            builder.Append("        router.RegisterWorker<global::");
            builder.Append(request.RequestType);
            builder.Append(", global::");
            builder.Append(request.ResponseType);
            builder.Append(">(");
            builder.Append(request.HandlerName);
            builder.AppendLine(");");
            return;
        }

        builder.Append("        router.Register<global::");
        builder.Append(request.RequestType);
        builder.AppendLine(">(");
        builder.Append("            ");
        builder.Append(CreateRoomIdResolver(request));
        builder.AppendLine(",");
        builder.Append("            canCreateRoom: ");
        builder.Append(request.CanCreateRoom ? "true" : "false");
        builder.AppendLine(",");
        builder.Append("            successConnectionAction: global::GameServer.Core.Rooms.RoomRequestConnectionAction.");
        builder.Append(request.SuccessConnectionAction);
        builder.AppendLine(",");
        builder.Append("            roomNotFoundErrorCode: global::Network.ErrorCode.");
        builder.Append(request.RoomNotFoundErrorCode);
        builder.AppendLine(");");
    }

    private static string CreateRoomIdResolver(RoomRequestInfo request)
    {
        string messageRoomId = "req." + request.RoomIdMemberName;
        return request.RoomIdSource switch
        {
            "Message" => "(req, context) => " + messageRoomId,
            "BoundConnection" => "(req, context) => context.RoomId",
            "MessageOrBoundConnection" =>
                "(req, context) => !global::System.String.IsNullOrWhiteSpace(" + messageRoomId + ") ? " +
                messageRoomId + " : context.RoomId",
            "MessageOrBoundConnectionOrDefault" =>
                "(req, context) => !global::System.String.IsNullOrWhiteSpace(" + messageRoomId + ") ? " +
                messageRoomId +
                " : (!global::System.String.IsNullOrWhiteSpace(context.RoomId) ? context.RoomId : " +
                SyntaxFactory.Literal(request.DefaultRoomId) + ")",
            _ => throw new InvalidOperationException(
                $"unsupported RoomId source {request.RoomIdSource}: {request.RequestType}"),
        };
    }
}
