using System.Text;

namespace Game001.CodeGenerator;

public sealed class RoomRpcGenerationStep : ICodeGenerationStep
{
    public string Name => "room-rpc";

    public CodeGenerationResult Execute(CodeGenerationContext context, CSharpSourceCatalog coreSources)
    {
        RoomRpcCatalog catalog = RoomRpcCatalog.Collect(coreSources);
        GeneratedFileChange[] changes =
        {
            GeneratedFileWriter.WriteIfChanged(
                Path.Combine(context.GeneratedRuntimeDirectory, "Game001RpcMessages.g.cs"),
                GenerateShared(catalog)),
            GeneratedFileWriter.WriteIfChanged(
                Path.Combine(context.RoomGeneratedDirectory, "Game001RoomRpc.g.cs"),
                GenerateServer(catalog)),
            GeneratedFileWriter.WriteIfChanged(
                Path.Combine(context.UnityClientGeneratedDirectory, "Game001Rpc.g.cs"),
                GenerateClient(catalog)),
        };
        return new CodeGenerationResult(
            changes.Count(item => item == GeneratedFileChange.Created),
            changes.Count(item => item == GeneratedFileChange.Updated),
            changes.Count(item => item == GeneratedFileChange.Unchanged));
    }

    private static string GenerateShared(RoomRpcCatalog catalog)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        AppendMessages(builder, catalog);
        return builder.ToString();
    }

    private static string GenerateServer(RoomRpcCatalog catalog)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine();
        builder.AppendLine("namespace Game001.Core.Generated");
        builder.AppendLine("{");
        AppendServerHandlerInterface(builder, catalog);
        AppendClientRoot(builder, catalog);
        foreach (RoomRpcContractInfo contract in catalog.Contracts.Where(HasClientMethods))
        {
            AppendClientProxy(builder, contract);
        }
        AppendServerRegistration(builder, catalog);
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string GenerateClient(RoomRpcCatalog catalog)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine();
        builder.AppendLine("namespace Game001.Core.Generated");
        builder.AppendLine("{");
        AppendClientHandlerInterface(builder, catalog);
        AppendServerRoot(builder, catalog);
        foreach (RoomRpcContractInfo contract in catalog.Contracts.Where(HasServerMethods))
        {
            AppendServerProxy(builder, contract);
        }
        AppendClientRegistration(builder, catalog);
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendServerHandlerInterface(StringBuilder builder, RoomRpcCatalog catalog)
    {
        builder.AppendLine("    public interface IGame001ServerRpcHandlers");
        builder.AppendLine("    {");
        foreach (RoomRpcMethodInfo method in GetMethods(catalog, RoomRpcDirection.Server))
        {
            builder.Append("        void ");
            builder.Append(method.HandlerName);
            builder.Append("(global::GameServer.Core.Rooms.RoomServerRpcContext context");
            AppendParameters(builder, method.Parameters, true);
            builder.AppendLine(");");
        }
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void AppendClientHandlerInterface(StringBuilder builder, RoomRpcCatalog catalog)
    {
        builder.AppendLine("    public interface IGame001ClientRpcHandlers");
        builder.AppendLine("    {");
        foreach (RoomRpcMethodInfo method in GetClientMethods(catalog))
        {
            builder.Append("        void ");
            builder.Append(method.HandlerName);
            builder.Append("(int entityId");
            AppendParameters(builder, method.Parameters, true);
            builder.AppendLine(");");
        }
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void AppendServerRoot(StringBuilder builder, RoomRpcCatalog catalog)
    {
        builder.AppendLine("    public sealed class Game001ServerRpcs");
        builder.AppendLine("    {");
        builder.AppendLine("        private readonly global::GameServer.Core.Rooms.IRoomServerRpcSender _sender;");
        builder.AppendLine();
        builder.AppendLine("        public Game001ServerRpcs(global::GameServer.Core.Rooms.IRoomServerRpcSender sender)");
        builder.AppendLine("        {");
        builder.AppendLine("            _sender = sender;");
        builder.AppendLine("        }");
        foreach (RoomRpcContractInfo contract in catalog.Contracts.Where(HasServerMethods))
        {
            builder.AppendLine();
            builder.Append("        public ");
            builder.Append(contract.AccessorName);
            builder.Append("ServerRpcProxy ");
            builder.Append(contract.AccessorName);
            builder.AppendLine("(int entityId)");
            builder.AppendLine("        {");
            builder.Append("            return new ");
            builder.Append(contract.AccessorName);
            builder.AppendLine("ServerRpcProxy(_sender, entityId);");
            builder.AppendLine("        }");
        }
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void AppendClientRoot(StringBuilder builder, RoomRpcCatalog catalog)
    {
        builder.AppendLine("    public sealed class Game001ClientRpcs");
        builder.AppendLine("    {");
        builder.AppendLine("        private readonly global::GameServer.Core.Rooms.IRoomClientRpcSender _sender;");
        builder.AppendLine();
        builder.AppendLine("        public Game001ClientRpcs(global::GameServer.Core.Rooms.IRoomClientRpcSender sender)");
        builder.AppendLine("        {");
        builder.AppendLine("            _sender = sender;");
        builder.AppendLine("        }");
        foreach (RoomRpcContractInfo contract in catalog.Contracts.Where(HasClientMethods))
        {
            builder.AppendLine();
            builder.Append("        public ");
            builder.Append(contract.AccessorName);
            builder.Append("ClientRpcProxy ");
            builder.Append(contract.AccessorName);
            builder.AppendLine("(int entityId)");
            builder.AppendLine("        {");
            builder.Append("            return new ");
            builder.Append(contract.AccessorName);
            builder.AppendLine("ClientRpcProxy(_sender, entityId);");
            builder.AppendLine("        }");
        }
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void AppendServerProxy(StringBuilder builder, RoomRpcContractInfo contract)
    {
        builder.Append("    public readonly struct ");
        builder.Append(contract.AccessorName);
        builder.AppendLine("ServerRpcProxy");
        builder.AppendLine("    {");
        builder.AppendLine("        private readonly global::GameServer.Core.Rooms.IRoomServerRpcSender _sender;");
        builder.AppendLine("        private readonly int _entityId;");
        builder.AppendLine();
        builder.Append("        public ");
        builder.Append(contract.AccessorName);
        builder.AppendLine("ServerRpcProxy(global::GameServer.Core.Rooms.IRoomServerRpcSender sender, int entityId)");
        builder.AppendLine("        {");
        builder.AppendLine("            _sender = sender;");
        builder.AppendLine("            _entityId = entityId;");
        builder.AppendLine("        }");
        foreach (RoomRpcMethodInfo method in contract.Methods.Where(item => item.Direction == RoomRpcDirection.Server))
        {
            AppendProxyMethod(builder, contract, method, "Send");
        }
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void AppendClientProxy(StringBuilder builder, RoomRpcContractInfo contract)
    {
        builder.Append("    public readonly struct ");
        builder.Append(contract.AccessorName);
        builder.AppendLine("ClientRpcProxy");
        builder.AppendLine("    {");
        builder.AppendLine("        private readonly global::GameServer.Core.Rooms.IRoomClientRpcSender _sender;");
        builder.AppendLine("        private readonly int _entityId;");
        builder.AppendLine();
        builder.Append("        public ");
        builder.Append(contract.AccessorName);
        builder.AppendLine("ClientRpcProxy(global::GameServer.Core.Rooms.IRoomClientRpcSender sender, int entityId)");
        builder.AppendLine("        {");
        builder.AppendLine("            _sender = sender;");
        builder.AppendLine("            _entityId = entityId;");
        builder.AppendLine("        }");
        foreach (RoomRpcMethodInfo method in contract.Methods.Where(item => item.Direction == RoomRpcDirection.Client))
        {
            AppendProxyMethod(builder, contract, method, "SendObservers");
        }
        if (contract.Methods.Any(item => item.Direction == RoomRpcDirection.Target))
        {
            builder.AppendLine();
            builder.Append("        public ");
            builder.Append(contract.AccessorName);
            builder.AppendLine("TargetRpcProxy Target(int connectionId)");
            builder.AppendLine("        {");
            builder.Append("            return new ");
            builder.Append(contract.AccessorName);
            builder.AppendLine("TargetRpcProxy(_sender, _entityId, connectionId);");
            builder.AppendLine("        }");
        }
        builder.AppendLine("    }");
        builder.AppendLine();

        if (!contract.Methods.Any(item => item.Direction == RoomRpcDirection.Target))
        {
            return;
        }

        builder.Append("    public readonly struct ");
        builder.Append(contract.AccessorName);
        builder.AppendLine("TargetRpcProxy");
        builder.AppendLine("    {");
        builder.AppendLine("        private readonly global::GameServer.Core.Rooms.IRoomClientRpcSender _sender;");
        builder.AppendLine("        private readonly int _entityId;");
        builder.AppendLine("        private readonly int _connectionId;");
        builder.AppendLine();
        builder.Append("        public ");
        builder.Append(contract.AccessorName);
        builder.AppendLine("TargetRpcProxy(global::GameServer.Core.Rooms.IRoomClientRpcSender sender, int entityId, int connectionId)");
        builder.AppendLine("        {");
        builder.AppendLine("            _sender = sender;");
        builder.AppendLine("            _entityId = entityId;");
        builder.AppendLine("            _connectionId = connectionId;");
        builder.AppendLine("        }");
        foreach (RoomRpcMethodInfo method in contract.Methods.Where(item => item.Direction == RoomRpcDirection.Target))
        {
            AppendProxyMethod(builder, contract, method, "SendTarget");
        }
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void AppendProxyMethod(
        StringBuilder builder,
        RoomRpcContractInfo contract,
        RoomRpcMethodInfo method,
        string sendMethod)
    {
        builder.AppendLine();
        builder.Append("        public void ");
        builder.Append(method.MethodName);
        builder.Append("(");
        AppendParameters(builder, method.Parameters, false);
        builder.AppendLine(")");
        builder.AppendLine("        {");
        builder.Append("            var message = new global::Game001.Core.Generated.Rpc.");
        builder.Append(method.MessageShortName);
        builder.AppendLine();
        builder.AppendLine("            {");
        builder.AppendLine("                EntityId = _entityId,");
        foreach (RoomRpcParameterInfo parameter in method.Parameters)
        {
            builder.Append("                ");
            builder.Append(parameter.FieldName);
            builder.Append(" = ");
            builder.Append(parameter.Name);
            builder.AppendLine(",");
        }
        builder.AppendLine("            };");
        builder.Append("            _sender.");
        builder.Append(sendMethod);
        builder.Append("<global::Game001.Core.Generated.Rpc.");
        builder.Append(method.MessageShortName);
        builder.Append(", ");
        builder.Append(contract.ComponentType);
        builder.Append(">(");
        if (method.Direction == RoomRpcDirection.Target)
        {
            builder.Append("_connectionId, ");
        }
        builder.Append("message");
        if (method.Direction == RoomRpcDirection.Client)
        {
            builder.Append(method.Option ? ", true" : ", false");
        }
        builder.AppendLine(");");
        builder.AppendLine("        }");
    }

    private static void AppendServerRegistration(StringBuilder builder, RoomRpcCatalog catalog)
    {
        builder.AppendLine("    public static class Game001RpcRegistration");
        builder.AppendLine("    {");
        builder.AppendLine("        public static void RegisterServer(");
        builder.AppendLine("            global::GameServer.Core.Rooms.IRoomServerRpcRegistry registry,");
        builder.AppendLine("            IGame001ServerRpcHandlers handlers)");
        builder.AppendLine("        {");
        foreach ((RoomRpcContractInfo contract, RoomRpcMethodInfo method) in GetContractMethods(catalog, RoomRpcDirection.Server))
        {
            builder.Append("            registry.Register<global::Game001.Core.Generated.Rpc.");
            builder.Append(method.MessageShortName);
            builder.Append(", ");
            builder.Append(contract.ComponentType);
            builder.Append(">(");
            builder.Append(method.Option ? "true" : "false");
            builder.AppendLine(", (context, message) =>");
            builder.AppendLine("            {");
            builder.Append("                handlers.");
            builder.Append(method.HandlerName);
            builder.Append("(context");
            AppendMessageArguments(builder, method.Parameters);
            builder.AppendLine(");");
            builder.AppendLine("            });");
        }
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static void AppendClientRegistration(StringBuilder builder, RoomRpcCatalog catalog)
    {
        builder.AppendLine("    public static class Game001RpcRegistration");
        builder.AppendLine("    {");
        builder.AppendLine();
        builder.AppendLine("        public static void RegisterClient(");
        builder.AppendLine("            global::GameServer.Core.Rooms.IRoomClientRpcRegistry registry,");
        builder.AppendLine("            IGame001ClientRpcHandlers handlers)");
        builder.AppendLine("        {");
        foreach ((RoomRpcContractInfo contract, RoomRpcMethodInfo method) in GetClientContractMethods(catalog))
        {
            builder.Append("            registry.Register<global::Game001.Core.Generated.Rpc.");
            builder.Append(method.MessageShortName);
            builder.Append(", ");
            builder.Append(contract.ComponentType);
            builder.AppendLine(">((entityId, message) =>");
            builder.AppendLine("            {");
            builder.Append("                handlers.");
            builder.Append(method.HandlerName);
            builder.Append("(entityId");
            AppendMessageArguments(builder, method.Parameters);
            builder.AppendLine(");");
            builder.AppendLine("            });");
        }
        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    private static void AppendMessages(StringBuilder builder, RoomRpcCatalog catalog)
    {
        builder.AppendLine();
        builder.AppendLine("namespace Game001.Core.Generated.Rpc");
        builder.AppendLine("{");
        foreach (RoomRpcContractInfo contract in catalog.Contracts)
        {
            foreach (RoomRpcMethodInfo method in contract.Methods)
            {
                builder.AppendLine("    [global::MemoryPack.MemoryPackable]");
                builder.Append("    public partial struct ");
                builder.Append(method.MessageShortName);
                builder.Append(" : ");
                builder.Append(method.Direction == RoomRpcDirection.Server
                    ? "global::GameServer.Core.Rooms.IRoomCommand"
                    : "global::GameServer.Core.Rooms.IRoomPush");
                builder.AppendLine(", global::GameServer.Core.Rooms.IRoomEntityRpcMessage");
                builder.AppendLine("    {");
                builder.AppendLine("        public int EntityId;");
                foreach (RoomRpcParameterInfo parameter in method.Parameters)
                {
                    builder.Append("        public ");
                    builder.Append(parameter.TypeName);
                    builder.Append(" ");
                    builder.Append(parameter.FieldName);
                    builder.AppendLine(";");
                }
                builder.AppendLine();
                builder.AppendLine("        int global::GameServer.Core.Rooms.IRoomEntityRpcMessage.EntityId => EntityId;");
                builder.AppendLine("    }");
                builder.AppendLine();
            }
        }
        builder.AppendLine("}");
    }

    private static void AppendParameters(
        StringBuilder builder,
        IReadOnlyList<RoomRpcParameterInfo> parameters,
        bool leadingComma)
    {
        for (int i = 0; i < parameters.Count; i++)
        {
            if (leadingComma || i > 0)
            {
                builder.Append(", ");
            }
            builder.Append(parameters[i].TypeName);
            builder.Append(" ");
            builder.Append(parameters[i].Name);
        }
    }

    private static void AppendMessageArguments(
        StringBuilder builder,
        IReadOnlyList<RoomRpcParameterInfo> parameters)
    {
        foreach (RoomRpcParameterInfo parameter in parameters)
        {
            builder.Append(", message.");
            builder.Append(parameter.FieldName);
        }
    }

    private static bool HasServerMethods(RoomRpcContractInfo contract)
    {
        return contract.Methods.Any(item => item.Direction == RoomRpcDirection.Server);
    }

    private static bool HasClientMethods(RoomRpcContractInfo contract)
    {
        return contract.Methods.Any(item => item.Direction != RoomRpcDirection.Server);
    }

    private static IEnumerable<RoomRpcMethodInfo> GetMethods(RoomRpcCatalog catalog, RoomRpcDirection direction)
    {
        return catalog.Contracts.SelectMany(contract => contract.Methods)
            .Where(method => method.Direction == direction);
    }

    private static IEnumerable<RoomRpcMethodInfo> GetClientMethods(RoomRpcCatalog catalog)
    {
        return catalog.Contracts.SelectMany(contract => contract.Methods)
            .Where(method => method.Direction != RoomRpcDirection.Server);
    }

    private static IEnumerable<(RoomRpcContractInfo Contract, RoomRpcMethodInfo Method)> GetContractMethods(
        RoomRpcCatalog catalog,
        RoomRpcDirection direction)
    {
        return catalog.Contracts.SelectMany(contract => contract.Methods
            .Where(method => method.Direction == direction)
            .Select(method => (contract, method)));
    }

    private static IEnumerable<(RoomRpcContractInfo Contract, RoomRpcMethodInfo Method)> GetClientContractMethods(
        RoomRpcCatalog catalog)
    {
        return catalog.Contracts.SelectMany(contract => contract.Methods
            .Where(method => method.Direction != RoomRpcDirection.Server)
            .Select(method => (contract, method)));
    }
}
