// <auto-generated />
using FishGame;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FishGame.Migrations
{
    [DbContext(typeof(FishGameContext))]
    [Migration("20241223115822_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FishGame.LongConfig", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<long>("value")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("configs");
                });

            modelBuilder.Entity("FishGame.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("online")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("uid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("nickname")
                        .IsUnique();

                    b.HasIndex("uid")
                        .IsUnique();

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
