// <auto-generated />
using FishGame;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FishGame.Migrations
{
    [DbContext(typeof(FishGameContext))]
    partial class FishGameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FishGame.UintConfig", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<uint>("value")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("configs");
                });

            modelBuilder.Entity("FishGame.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("gameState")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("globalState")
                        .HasColumnType("INTEGER");

                    b.Property<float>("lastActionTimeSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("macToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("nickname")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("macToken")
                        .IsUnique();

                    b.HasIndex("nickname")
                        .IsUnique();

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
